baseURL = "https://games.sinzmise.top"
languageCode = "zh-hans"
title = "SinZero游戏之家"
theme = "maupassant"

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

[author]
  name = "SinzMise"

[params]
  author = "SinzMise"
  subtitle = "致力于收集那些好玩的小游戏"
  keywords = "flash小游戏,H5小游戏,网页小游戏"
  description = "致力于收集那些好玩的小游戏"
  busuanzi = true #启用不算子网页统计
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "SinzMise的小屋（九弦之屋）"
  name = "SinzMise的小屋（九弦之屋）"
  url = "https://blog.sinzmise.top/"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "h5"
    name = "h5小游戏"
    url = "/categories/h5/"
    weight = 2

  [[menu.main]]
    identifier = "flash"
    name = "flash小游戏"
    url = "/categories/flash/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
